// vue-demos/basic_demo/src/App.vue
<template>
  <div>
    <v-stage
      ref="stage"
      :config="configKonva"
      @dragstart="handleDragstart"
      @dragend="handleDragend"
    >
      <v-layer ref="layer">
        <v-star
          v-for="item in list"
          :key="item.id"
          :config="{
            x: item.x,
            y: item.y,
            rotation: item.rotation,
            id: item.id,
            numPoints: 5,
            innerRadius: 30,
            outerRadius: 50, fill: '#89b717',
            opacity: 0.8,
            draggable: true,
            scaleX: dragItemId === item.id ? item.scale * 1.2 : item.scale,
            scaleY: dragItemId === item.id ? item.scale * 1.2 : item.scale,
            shadowColor: 'black',
            shadowBlur: 10,
            shadowOffsetX: dragItemId === item.id ? 15 : 5,
            shadowOffsetY: dragItemId === item.id ? 15 : 5,
            shadowOpacity: 0.6
          }"
        ></v-star>
      </v-layer>
    </v-stage>
  </div>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;
export default {
  data() {
    return {
      list: [],
      dragItemId: null,
      configKonva: {
        width: width,
        height: height
      }
    };
  },
  methods: {
    handleDragstart(e) {
      // save drag element:
      this.dragItemId = e.target.id();
      // move current element to the top:
      const item = this.list.find((i = i.id === this.dragItemId));
      const index = this.list.indexOf(item);
      this.list.splice(index, 1);
      this.list.push(item);
    },
    handleDragend(e) {
      this.dragItemId = null;
    }
  },
  mounted() {
    for (let n = 0; n < 30; n++) {
      this.list.push({
        id: Math.round(Math.random() * 10000).toString(),
        x: Math.random() * width,
        y: Math.random() * height,
        rotation: Math.random() * 180,
        scale: Math.random()
      });
    }
  }
};
</script>

<style>
body {
  margin: 0;
  padding: 0;
}
</style>

// svelte-demos/cache/App.svelte
<script>
  import { Stage, Layer, Group, Star } from "svelte-konva";

  let group;
  let shouldCache = false;

  const list = [];

  for (let n = 0; n < 300; n++) {
    list.push({
      id: n.toString(),
      x: Math.random() * window.innerWidth,
      y: Math.random() * window.innerHeight,
      rotation: Math.random() * 180,
      scale: Math.random(),
    });
  }

  $: if (group) {
    if (shouldCache) {
      group.cache();
    } else {
      group.clearCache();
    }
  }
</script>

<div>
  <Stage
    config={{
      width: window.innerWidth,
      height: window.innerHeight,
      draggable: true,
    }}
  >
    <Layer>
      <Group bind:handle={group}>
        {#each list as item}
          <Star
            config={{
              x: item.x,
              y: item.y,
              rotation: item.rotation,
              id: item.id,
              numPoints: 5,
              innerRadius: 30,
              outerRadius: 50,
              fill: "#89b717",
              opacity: 0.8,
              shadowColor: "black",
              shadowBlur: 10,
              shadowOpacity: 0.6,
              scaleX: item.scale,
              scaleY: item.scale,
            }}
          />
        {/each}
      </Group>
    </Layer>
  </Stage>

  <div class="cache">
    <input type="checkbox" bind:checked={shouldCache} /> cache shapes
  </div>
</div>

<style>
  .cache {
    position: absolute;
    top: 0;
    left: 0;
  }
</style>
