// vue-demos/custom_shape/src/App.vue
<template>
    <v-stage ref="stage" :config="stageSize">
      <v-layer>
        <v-shape :config="{
        sceneFunc: function(context, shape) {
          context.beginPath();
          context.moveTo(20, 50);
          context.lineTo(220, 80);
          context.quadraticCurveTo(150, 100, 260, 170);
          context.closePath();

          // special Konva.js method
          context.fillStrokeShape(shape);
        },
        fill: '#00D2FF',
        stroke: 'black',
        strokeWidth: 4
      }"/>
    </v-layer>
  </v-stage>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;

export default {
  data() {
    return {
      stageSize: {
        width: width,
        height: height
      }
    };
  }
};
</script>

// svelte-demos/drag_and_drop/src/App.svelte
<script>
    import { Stage, Layer, Text } from "svelte-konva";

    let isDragging = false;

    let config = {
        text: "Draggable Text",
        x: 50,
        y: 50,
        draggable: true,
    };

    $: config.fill = isDragging ? "green" : "black";
</script>

<Stage config={{ width: window.innerWidth, height: window.innerHeight }}>
    <Layer>
        <Text
            {config}
            on:dragstart={() => (isDragging = true)}
            on:dragend={() => (isDragging = false)}
        />
    </Layer>
</Stage>
