// vue-demos/filters/src/App.vue
<template>
<v-stage ref="stage" :config="stageSize">
      <v-layer ref="layer">
        <v-rect
          ref="rect"
          @mousemove="handleMouseMove"
          :config="{
            filters: filters,
            noise: 1,
            x: 10,
            y: 10,
            width: 50,
            height: 50,
            fill: color,
            shadowBlur: 10
          }"
        />
      </v-layer>
    </v-stage>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;
import Konva from 'konva';

export default {
  data() {
    return {
      stageSize: {
        width: width,
        height: height
      },
      color: 'green',
      filters: [Konva.Filters.Noise]
    };
  },
  methods: {
    handleMouseMove() {
      this.color = Konva.Util.getRandomColor();
      // recache
      const rectNode = this.$refs.rect.getNode();
      // may need to redraw layer manually
      rectNode.cache();
    }
  },
  mounted() {
    const rectNode = this.$refs.rect.getNode();
    rectNode.cache();
  },
};
</script>

// svelte-demos/filters/App.svelte
<script>
  import Konva from "konva";
  import { Stage, Layer, Rect } from "svelte-konva";
  import { onMount, tick } from "svelte";

  let rectangle;
  let color = "green";

  function handleMouseMove() {
    color = Konva.Util.getRandomColor();
    // may need to redraw layer manually due to possible color change
    rectangle.cache();
  }

  onMount(async () => {
    // wait for the rectangle handle to be rendered and become defined
    await tick();

    rectangle.cache();
  });
</script>

<Stage config={{ width: window.innerWidth, height: window.innerHeight }}>
  <Layer>
    <Rect
      config={{
        filters: [Konva.Filters.Noise],
        noise: 1,
        x: 10,
        y: 10,
        width: 50,
        height: 50,
        fill: color,
        shadowBlur: 10,
      }}
      bind:handle={rectangle}
      on:mousemove={handleMouseMove}
    />
  </Layer>
</Stage>
