// svelte-demos/images/App.svelte
<script>
	import { onMount, tick } from "svelte";
	import { Stage, Layer, Image } from "svelte-konva";

	let image = null;
	onMount(() => {
	  const img = document.createElement("img");
	  img.src = "https://konvajs.org/assets/yoda.jpg";
	  img.onload = () => {
	    image = img;
	  };
	});
</script>

<Stage config={{ width: 1000, height: 1000 }}>
  <Layer>
    <Image
      config={{ image }}
    />
  </Layer>
</Stage>

// vue-demos/images/src/App.vue
<template>
  <v-stage ref="stage" :config="stageSize">
    <v-layer ref="layer">
      <v-image :config="{
            image: image
          }"/>
    </v-layer>
  </v-stage>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;

export default {
  data() {
    return {
      stageSize: {
        width: width,
        height: height
      },
      image: null
    };
  },
  created() {
    const image = new window.Image();
    image.src = "https://konvajs.org/assets/yoda.jpg";
    image.onload = () => {
      // set image only when it is loaded
      this.image = image;
    };
  }
};
</script>
